# Generated by Django 5.1.4 on 2025-04-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('exp_reward', models.PositiveBigIntegerField()),
                ('time_required', models.TimeField()),
                ('difficulty', models.PositiveSmallIntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('streak', models.PositiveBigIntegerField()),
            ],
        ),
    ]
