# Generated by Django 5.1.4 on 2025-04-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='streak',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
