# Generated by Django 5.1.4 on 2025-04-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_habit_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='name',
            field=models.CharField(default='default_habit', max_length=255),
        ),
    ]
