# Generated by Django 5.1.7 on 2025-04-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_habit_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_required',
            field=models.IntegerField(),
        ),
    ]
