# Generated by Django 5.1.7 on 2025-04-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userprofile_next_level_exp_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_required',
            field=models.PositiveBigIntegerField(),
        ),
    ]
