# Generated by Django 5.1.7 on 2025-04-24 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_habit_time_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('name', models.CharField(default='default_habit', max_length=255)),
                ('exp_reward', models.PositiveBigIntegerField()),
                ('time_required', models.PositiveBigIntegerField()),
                ('difficulty', models.PositiveSmallIntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
