# Generated by Django 5.1.4 on 2025-04-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
