# Generated by Django 5.1.4 on 2025-04-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_habit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='reset',
            field=models.BooleanField(default=False),
        ),
    ]
