# Generated by Django 5.1.4 on 2025-04-30 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_userprofile_timezone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='reset',
            new_name='needs_reset',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='time',
            new_name='reset_time',
        ),
    ]
