# Generated by Django 5.1.4 on 2025-05-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_reset_habit_needs_reset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='streak',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
