# Generated by Django 5.1.4 on 2025-05-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_habit_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='difficulty',
            field=models.SmallIntegerField(),
        ),
    ]
