# Generated by Django 5.1.4 on 2025-05-06 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('name', models.CharField(default='NAME', max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('name', models.CharField(default='NAME_NODE', max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='skills.node')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node', to='skills.tree')),
            ],
        ),
    ]
