# Generated by Django 5.1.4 on 2025-05-10 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_node_root_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='root_node',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_tree', to='skills.node'),
        ),
    ]
