# Generated by Django 5.1.4 on 2025-05-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_tree_root_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='structure',
            field=models.JSONField(default='{}'),
        ),
    ]
