# Generated by Django 5.1.4 on 2025-05-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_node_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
