# Generated by Django 5.1.4 on 2025-05-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_node_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='skill_points',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
