# Generated by Django 5.1.4 on 2025-05-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0009_tree_skill_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='node',
            name='time_required',
            field=models.PositiveBigIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='tree',
            name='exp',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tree',
            name='skill_points',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
