# Generated by Django 5.1.4 on 2025-05-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0010_node_difficulty_node_time_required_tree_exp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='skill_points_required',
            field=models.PositiveBigIntegerField(default=60),
        ),
    ]
