# Generated by Django 5.1.4 on 2025-05-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0011_node_skill_points_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(default='NAME_NODE', max_length=45),
        ),
        migrations.AlterField(
            model_name='tree',
            name='name',
            field=models.CharField(default='NAME', max_length=45),
        ),
    ]
